# Disable CI triggers, we don't want a build per merge to Master
trigger: none

jobs:
  # Windows_NT leg
  - template: /eng/pipelines/standard-ci.yml
    parameters:
      name: Windows_NT
      pool:
        name: Hosted VS2017
      targetOS: Windows_NT

  # Linux leg (only runs in CI)
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/pipelines/standard-ci.yml
      parameters:
        name: Linux
        pool:
          name: Hosted Ubuntu 1604
        targetOS: Linux

  # OSX leg (only runs in CI)
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/pipelines/standard-ci.yml
      parameters:
        name: OSX
        pool:
          name: Hosted macOS
        targetOS: OSX