parameters:
  name: ''
  pool: {}
  strategy: {}
  targetOS: ''

jobs:
  - job: ${{ parameters.name }}
    variables:
      # OS Specific commands
      ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: build.cmd -c -ci
      ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: ./build.sh -c --ci
      ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
        __env: SET
      ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
        __env: printenv

    pool:
      ${{ insert }}: ${{ parameters.pool }}
    strategy:
      maxParallel: 99
      ${{ insert }}: ${{ parameters.strategy }}

    steps:
      - script: $(__env)
        displayName: Print Env
      - script: $(_buildScript)
        displayName: Build
        continueOnError: true
      - script: $(__env)
        displayName: Print Env