parameters:
  name: ''
  pool: {}
  strategy: {}
  targetOS: ''

jobs:
  - job: ${{ parameters.name }}
    variables:
      # OS Specific commands
      ${{ if eq(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: build.cmd -c -ci
      ${{ if ne(parameters.targetOS, 'Windows_NT') }}:
        _buildScript: ./build.sh --ci

    pool:
      ${{ insert }}: ${{ parameters.pool }}
    strategy:
      maxParallel: 99
      ${{ insert }}: ${{ parameters.strategy }}

    steps:
      - script: $(_buildScript)
        displayName: Build